image: jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

stages:
  - test
  - assembleDebug
  - deployDebug
  - assembleRelease
  - deployRelease

testDebug:
  stage: test
  only:
    - develop
  script:
    - ./gradlew -Pci --console=plain testDebug

assembleDebug:
  stage: assembleDebug
  only:
    - develop
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug

deployDebug:
  stage: deployDebug
  only:
    - develop
  script:
    - |
      curl \
        -F token="${APK_SLACK_CHANNEL_ACCESS_TOKEN}" \
        -F channels="${APK_SLACK_CHANNEL_ID}" \
        -F initial_comment="Hello Team! Here is the latest Photo Monkey debug APK" \
        -F "file=@$(find app/build/outputs/apk/debug -name '*photomonkey*')" \
        https://slack.com/api/files.upload
  cache: {}

testRelease:
  stage: test
  only:
    - tags
  script:
    - ./gradlew -Pci --console=plain testRelease

assembleRelease:
  stage: assembleRelease
  only:
    - tags
  script:
    - echo $KEYSTORE_FILE | base64 -d > my.keystore
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$KEY_ALIAS
      -Pandroid.injected.signing.key.password=$KEY_PASSWORD
  artifacts:
    paths:
      - app/build/outputs/apk/release

deployRelease:
  stage: deployRelease
  only:
    - tags
  script:
    - |
      curl \
        -F token="${APK_SLACK_CHANNEL_ACCESS_TOKEN}" \
        -F channels="${APK_SLACK_CHANNEL_ID}" \
        -F initial_comment="Hello Team! Here is the latest Photo Monkey release APK" \
        -F "file=@$(find app/build/outputs/apk/release -name 'photomonkey*')" \
        https://slack.com/api/files.upload
  cache: {}